ALTER TYPE "InventoryVertical" ADD VALUE IF NOT EXISTS 'PHARMACY';
ALTER TYPE "InventoryVertical" ADD VALUE IF NOT EXISTS 'ELECTRONICS';
ALTER TYPE "InventoryVertical" ADD VALUE IF NOT EXISTS 'STATIONERY';
ALTER TYPE "InventoryVertical" ADD VALUE IF NOT EXISTS 'HARDWARE';
